import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Page } from "@navikt/ds-react";
import { PageBlock } from "@navikt/ds-react/Page";
import "@navikt/ds-css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div
          id="aria-live-errors"
          aria-live="polite"
          aria-relevant="additions"
          className="sr-only"
        />
        <Page>
          <PageBlock width="lg">{children}</PageBlock>
        </Page>
      </body>
    </html>
  );
}
